baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Neuromancer'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = "Jacopo Barone"
  favicon = ""
  site_logo = ""
  custom_css = ["custom.css"]
  description = "The last theme you'll ever need. Maybe."
  recent_posts_number = 3
  date_format = "2 January 2006"
  show_reading_time = true
  [[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/baronej/"
    label = "LinkedIn"
    color = "#0077b5"